groups:
  - name: ha_webstack_alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "Target {{ $labels.job }} on {{ $labels.instance }} has been unreachable for 1 minute."

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[2m])) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High P95 latency detected"
          description: "P95 request latency exceeds 500ms over 2 minutes."

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[2m])) / sum(rate(http_requests_total[2m])) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx Error Rate"
          description: "5xx HTTP error rate is above 5% over 2 minutes."
